export let sponsors=[
    {
        "name":"sponsor",
        "link":"www.google.com",
        "img":"a.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
    {
        "name":"sponsor1",
        "link":"www.youtube.com",
        "img":"../assets/images/ieeelogo.png"
    },
]